server:
  port: 6062

bank:
  middleware:
    url: http://localhost:8080

spring:
  application:
    name: beneficiary-service
  profiles:
    active: mock
#  mock:
#    enabled: true
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    com.bank.retail: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

beneficiary:
  cooling-time-minutes: 30