# Mock Profile Configuration
# This profile is used for Mock/Testing environment
mock:
  enabled: true
spring:
  application:
    name: beneficiary-service-mock
  # Database Configuration - H2 In-Memory Database for Mock
  datasource:
    url: jdbc:postgresql://34.18.104.74:5432/dukhanbank
    username: postgres
    password: Poclab_123#
    driver-class-name: org.postgresql.Driver
  # JPA Configuration for H2
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # H2 Console
  h2:
    console:
      enabled: true
  
  # Redis Configuration
  data:
    redis:
      host: 34.18.60.8
      port: 6379
      password: XU0/QICjAcFPZC3O/2PmkZkocWWpnZUAEPGMQBK7Y6Kxh0hlJIIU0+Ir4Squbxb2bsRXgBCvacs2oHVc
      username: default
      timeout: 30000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 5
          max-wait: 10000ms

# Logging Configuration for Mock
logging:
  level:
    com.dbx.bo: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application Configuration
app:
  mockEnabled: true
  testing:
    bypass-session-token: false
    otp-static: "111111"
  common-service:
    url: http://localhost:8082
    otp-notification-id: "8729"
    mock-enabled: true

# OTP Configuration
# otp:
#   validity-minutes: 10
#   length: 6
#   max-regeneration-count: 5
#   max-attempts: 3
#   testing:
#     enabled: false
#     static-value: "111111"
#     description: "Testing mode - using static OTP"